name: DeployJSON
env:
  OUTPUT_PATH: ${{ github.workspace }}

on:
    push:
      branches:
        - master

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      # checkout code from repo
      - name: checkout code from repo
        uses: actions/checkout@master
        
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM Template
        env:
          RESOURCE_GROUP: rg-appservice-test-01
          RESOURCE_GROUP_REGION: northeurope
          DEPLOYMENTNAME: appservicedeployment01
          TEMPLATEFILE: ../../azuredeploy.json
          PARAMETERSFILE: ../../azuredeploy.parameters.json      
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create --name $env:DEPLOYMENTNAME --resource-group $env:RESOURCEGROUPNAME --template-file $env:TEMPLATEFILE --parameters $env:PARAMETERSFILE  
