name: DeployJSON
env:
  OUTPUT_PATH: ${{ github.workspace }}

on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

jobs:
  build:
    runs-on: windows-latest
 
    steps:
      # checkout code from repo
      - name: checkout code from repo
        uses: actions/checkout@v1
        
      - name: find powershell file
        run: |
          ls '${{ env.OUTPUT_PATH }}'
               
      - name: deploy json

        env:

          RESOURCE_GROUP: rg-githubdeployment

          RESOURCE_GROUP_REGION: northeurope
          
          DEPLOYMENTNAME: jsondeploy
          
          TEMPLATEFILE: https://raw.githubusercontent.com/alankinane/simplewebapp/master/azuredeploy.json
          
          PARAMETERSFILE: https://raw.githubusercontent.com/alankinane/simplewebapp/master/azuredeploy.parameters.json

        run: >      
          powershell -command "& '${{ env.OUTPUT_PATH }}\deploy.ps1'"
          -servicePrincipal ${{ secrets.SERVICE_PRINCIPAL_APPID }}
          -servicePrincipalSecret ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
          -servicePrincipalTenantId ${{ secrets.SERVICE_PRINCIPAL_TENANTID }}
          -azureSubscriptionName ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          -resourceGroupName %RESOURCE_GROUP%
          -resourceGroupNameRegion %RESOURCE_GROUP_REGION%         
          -deploymentname %DEPLOYMENTNAME%
          -templatefile %TEMPLATEFILE%
          -parametersfile %PARAMETERSFILE%
